version: '3.8'
services:
  car_reservation:
    container_name: car_reservation
    build: .
    ports:
      - "8000:8000"
      - "5030:5030"
    environment:
      - DATABASE_URL=jdbc:postgresql://pgsqlserver:5432/car_reservation_dev
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=vinny
    volumes:
      - ./:/app
    depends_on:
      - pgsqlserver

  flyway_car_res:
    container_name: flyway_car_res
    image: flyway/flyway:6.3.1
    command: -url=jdbc:postgresql://pgsqlserver:5432/car_reservation_dev -schemas=public -user=postgres -password=vinny -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=vinny
      - FLYWAY_URL=jdbc:postgresql://pgsqlserver:5432/car_reservation_dev
      - FLYWAY_HOST=pgsqlserver
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      pgsqlserver:
        condition: service_healthy

  pgsqlserver:
    image: postgres:12
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vinny
      - POSTGRES_DB=car_reservation_dev
    volumes:
      - pgsql_data:/var/lib/postgresql
      - pgsql_config:/etc/postgresql/conf.d
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
volumes:
  pgsql_data:
  pgsql_config:
